# coding: utf-8

import re

context_str = """
<a title=" Python编程 从入门到实践 第2版"  ddclick="act=normalResult_picture&pos=24003310_0_1_q" class="pic" name="itemlist-picture"  dd_name="单品图片" href="http://product.dangdang.com/24003310.html"  target="_blank" ><img src='http://img3m0.ddimg.cn/67/4/24003310-1_b_10.jpg' alt=' Python编程 从入门到实践 第2版' /><p class="cool_label"></p></a><p class="price" > <span class="price_n">&yen;61.40</span><a style="color: #878787;text-decoration:none;">定价：</a><span class="price_r">&yen;89.00</span><span class="price_s">(6.9折)</span></p><p class="name" name="title" ><a title=" Python编程 从入门到实践 第2版 " href="http://product.dangdang.com/24003310.html" ddclick="act=normalResult_title&pos=24003310_0_1_q" name="itemlist-title" dd_name="单品标题" target="_blank" > <font class="skcolor_ljg">Python</font>编程 从入门到实践 第2版 </a></p><p class="search_hot_word" >零基础学Python编程教程书籍，数据分析、网络爬虫、深度学习必备技能，畅销经典蟒蛇书升级版，附赠源代码、练习答案、学习视频、配套编程环境、学习速查地图读者交流群等资源。</p><p class="star" ><span class="level" ><span style="width: 90%;"></span></span><a href="http://product.dangdang.com/24003310.html?point=comment_point" target="_blank" name="itemlist-review" dd_name="单品评论" ddclick="act=click_review_count&pos=24003310_0_1_q">178973条评论</a></p><div class="empty_div"></div><span class="new_lable" y=""></span><span class="tag_box"></span><div class="shop_button"><p class="bottom_p"><a  class='search_btn_cart ' name='Buy' dd_name='加入购物车' href='javascript:AddToShoppingCart(24003310)' ddclick='act=normalResult_addToCart&pos=24003310_0_1_q'><span class='icon'></span>加入购物车</a><a class='search_btn_collect' name='collect' dd_name='加入收藏' id="lcase24003310" href="javascript:void(0);" name="Sc" ddclick='act=normalResult_favor&pos=24003310_0_1_q'>收藏</a></p></div>                </li>
                                <li ddt-pit="2" class="line2" id="p28486010">
                    <a title=" 零基础学Python（全彩版）"  ddclick="act=normalResult_picture&pos=28486010_1_1_q" class="pic" name="itemlist-picture"  dd_name="单品图片" href="http://product.dangdang.com/28486010.html"  target="_blank" ><img src='http://img3m0.ddimg.cn/47/6/28486010-1_b_26.jpg' alt=' 零基础学Python（全彩版）' /><p class="cool_label"></p></a><p class="price" > <span class="price_n">&yen;79.80</span><a style="color: #878787;text-decoration:none;">定价：</a><span class="price_r">&yen;79.80</span></p><p class="name" name="title" ><a title=" 零基础学Python（全彩版） " href="http://product.dangdang.com/28486010.html" ddclick="act=normalResult_title&pos=28486010_1_1_q" name="itemlist-title" dd_name="单品标题" target="_blank" > 零基础学<font class="skcolor_ljg">Python</font>（全彩版） </a></p><p class="search_hot_word" >Python3全新升级！超20万读者认可的彩色书，从基本概念到完整项目开发，助您快速掌握Python编程。全程视频+完整源码+215道课后题+实物魔卡+海量资源</p><p class="star" ><span class="level" ><span style="width: 90%;"></span></span><a href="http://product.dangdang.com/28486010.html?point=comment_point" target="_blank" name="itemlist-review" dd_name="单品评论" ddclick="act=click_review_count&pos=28486010_1_1_q">7309条评论</a></p><div class="empty_div"></div><span class="new_lable" y=""></span><span class="tag_box"></span><div class="shop_button"><p class="bottom_p"><a  class='search_btn_cart ' name='Buy' dd_name='加入购物车' href='javascript:AddToShoppingCart(28486010)' ddclick='act=normalResult_addToCart&pos=28486010_1_1_q'><span class='icon'></span>加入购物车</a><a class='search_btn_collect' name='collect' dd_name='加入收藏' id="lcase28486010" href="javascript:void(0);" name="Sc" ddclick='act=normalResult_favor&pos=28486010_1_1_q'>收藏</a></p></div>                </li>
                                <li ddt-pit="3" class="line3" id="p28534461">
                    <a title=" Python编程三剑客：Python编程从入门到实践第2版+Python编程快速上手+Python极客项目编程（当当套装"  ddclick="act=normalResult_picture&pos=28534461_2_2_q" class="pic" name="itemlist-picture"  dd_name="单品图片" href="http://product.dangdang.com/28534461.html"  target="_blank" ><img src='http://img3m1.ddimg.cn/87/24/28534461-1_b_3.jpg' alt=' Python编程三剑客：Python编程从入门到实践第2版+Python编程快速上手+Python极客项目编程（当当套装' /><p class="cool_label"></p></a><p class="price" > <span class="price_n">&yen;156.60</span><a style="color: #878787;text-decoration:none;">定价：</a><span class="price_r">&yen;227.00</span><span class="price_s">(6.9折)</span></p><p class="name" name="title" ><a title=" Python编程三剑客：Python编程从入门到实践第2版+Python编程快速上手+Python极客项目编程（当当套装 " href="http://product.dangdang.com/28534461.html" ddclick="act=normalResult_title&pos=28534461_2_2_q" name="itemlist-title" dd_name="单品标题" target="_blank" > <font class="skcolor_ljg">Python</font>编程三剑客：<font class="skcolor_ljg">Python</font>编程从入门到实践第2版+<font class="skcolor_ljg">Python</font>编程快速上手+<font class="skcolor_ljg">Python</font>极客项目编程（当当套装 </a></p><p class="search_hot_word" >Python编程畅销经典套装，Python入门零基础自学教程书籍，Python项目案例开发实战，一套书搞定Python编程</p><p class="star" ><span class="level" ><span style="width: 100%;"></span></span><a href="http://product.dangdang.com/28534461.html?point=comment_point" target="_blank" name="itemlist-review" dd_name="单品评论" ddclick="act=click_review_count&pos=28534461_2_2_q">3576条评论</a></p><div class="empty_div"></div><span class="new_lable" y=""></span><span class="tag_box"></span><div class="shop_button"><p class="bottom_p"><a  class='search_btn_cart ' name='Buy' dd_name='加入购物车' href='javascript:AddToShoppingCart(28534461)' ddclick='act=normalResult_addToCart&pos=28534461_2_2_q'><span class='icon'></span>加入购物车</a><a class='search_btn_collect' name='collect' dd_name='加入收藏' id="lcase28534461" href="javascript:void(0);" name="Sc" ddclick='act=normalResult_favor&pos=28534461_2_2_q'>收藏</a></p></div>                </li>
                                <li ddt-pit="4" class="line4" id="p23997502">
                    <a title=" Python编程快速上手 让繁琐工作自动化（Python3编程从入门到实践 新手学习必备用书）"  ddclick="act=normalResult_picture&pos=23997502_3_1_q" class="pic" name="itemlist-picture"  dd_name="单品图片" href="http://product.dangdang.com/23997502.html"  target="_blank" ><img src='http://img3m2.ddimg.cn/1/5/23997502-1_b_6.jpg' alt=' Python编程快速上手 让繁琐工作自动化（Python3编程从入门到实践 新手学习必备用书）' /><p class="cool_label"></p></a><p class="price" > <span class="price_n">&yen;66.20</span><a style="color: #878787;text-decoration:none;">定价：</a><span class="price_r">&yen;69.00</span><span class="price_s">(9.6折)</span></p><p class="name" name="title" ><a title=" Python编程快速上手 让繁琐工作自动化（Python3编程从入门到实践 新手学习必备用书） " href="http://product.dangdang.com/23997502.html" ddclick="act=normalResult_title&pos=23997502_3_1_q" name="itemlist-title" dd_name="单品标题" target="_blank" > <font class="skcolor_ljg">Python</font>编程快速上手 让繁琐工作自动化（<font class="skcolor_ljg">Python</font>3编程从入门到实践 新手学习必备用书） </a></p><p class="search_hot_word" >Python3编程从入门到实践美亚畅销Python编程入门图书 Python3实战指南 带你快速实现Python高效编程</p><p class="star" ><span class="level" ><span style="width: 90%;"></span></span><a href="http://product.dangdang.com/23997502.html?point=comment_point" target="_blank" name="itemlist-review" dd_name="单品评论" ddclick="act=click_review_count&pos=23997502_3_1_q">39497条评论</a></p><div class="empty_div"></div><span class="new_lable" y=""></span><span class="tag_box"></span><div class="shop_button"><p class="bottom_p"><a  class='search_btn_cart ' name='Buy' dd_name='加入购物车' href='javascript:AddToShoppingCart(23997502)' ddclick='act=normalResult_addToCart&pos=23997502_3_1_q'><span class='icon'></span>加入购物车</a><a class='search_btn_collect' name='collect' dd_name='加入收藏' id="lcase23997502" href="javascript:void(0);" name="Sc" ddclick='act=normalResult_favor&pos=23997502_3_1_q'>收藏</a></p></div>                </li>
                                <li ddt-pit="5" class="line5" id="p28510027">
                    <a title=" Python爬虫技术——深入理解原理、技术与开发"  ddclick="act=normalResult_picture&pos=28510027_4_1_q" class="pic" name="itemlist-picture"  dd_name="单品图片" href="http://product.dangdang.com/28510027.html"  target="_blank" ><img data-original='http://img3m7.ddimg.cn/7/10/28510027-1_b_6.jpg' src='images/model/guan/url_none.png' alt=' Python爬虫技术——深入理解原理、技术与开发' /><p class="cool_label"></p></a><p class="price" > <span class="price_n">&yen;61.40</span><a style="color: #878787;text-decoration:none;">定价：</a><span class="price_r">&yen;89.00</span><span class="price_s">(6.9折)</span></p><p class="name" name="title" ><a title=" Python爬虫技术——深入理解原理、技术与开发 " href="http://product.dangdang.com/28510027.html" ddclick="act=normalResult_title&pos=28510027_4_1_q" name="itemlist-title" dd_name="单品标题" target="_blank" > <font class="skcolor_ljg">Python</font>爬虫技术——深入理解原理、技术与开发 </a></p><p class="search_hot_word" >网红技术专家！JetBrains大中华区市场部经理赵磊作序！超过300个实战案例，10万行源代码，22个综合实战项目，海量学习资料！</p><p class="star" ><span class="level" ><span style="width: 100%;"></span></span><a href="http://product.dangdang.com/28510027.html?point=comment_point" target="_blank" name="itemlist-review" dd_name="单品评论" ddclick="act=click_review_count&pos=28510027_4_1_q">1422条评论</a></p><div class="empty_div"></div><span class="new_lable" y=""></span><span class="tag_box"></span><div class="shop_button"><p class="bottom_p"><a  class='search_btn_cart ' name='Buy' dd_name='加入购物车' href='javascript:AddToShoppingCart(28510027)' ddclick='act=normalResult_addToCart&pos=28510027_4_1_q'><span class='icon'></span>加入购物车</a><a class='search_btn_collect' name='collect' dd_name='加入收藏' id="lcase28510027" href="javascript:void(0);" name="Sc" ddclick='act=normalResult_favor&pos=28510027_4_1_q'>收藏</a></p></div>                </li>
                                <li ddt-pit="6" class="line6" id="p25312917">
                    <a title=" 利用Python进行数据分析（原书第2版）"  ddclick="act=normalResult_picture&pos=25312917_5_1_q" class="pic" name="itemlist-picture"  dd_name="单品图片" href="http://product.dangdang.com/25312917.html"  target="_blank" ><img data-original='http://img3m7.ddimg.cn/3/33/25312917-1_b_9.jpg' src='images/model/guan/url_none.png' alt=' 利用Python进行数据分析（原书第2版）' /><p class="cool_label"></p></a><p class="price" > <span class="price_n">&yen;82.10</span><a style="color: #878787;text-decoration:none;">定价：</a><span class="price_r">&yen;119.00</span><span class="price_s">(6.9折)</span></p><p class="name" name="title" ><a title=" 利用Python进行数据分析（原书第2版） " href="http://product.dangdang.com/25312917.html" ddclick="act=normalResult_title&pos=25312917_5_1_q" name="itemlist-title" dd_name="单品标题" target="_blank" > 利用<font class="skcolor_ljg">Python</font>进行数据分析（原书第2版） </a></p><p class="search_hot_word" >Python数据分析经典畅销书全新升级，第1版中文版累计销售100000册 Python pandas创始人亲自执笔，Python语言的核心开发人员鼎立推荐 针对Python 3.6进行全面修订和更新</p><p class="star" ><span class="level" ><span style="width: 90%;"></span></span><a href="http://product.dangdang.com/25312917.html?point=comment_point" target="_blank" name="itemlist-review" dd_name="单品评论" ddclick="act=click_review_count&pos=25312917_5_1_q">26483条评论</a></p><div class="empty_div"></div><span class="new_lable" y=""></span><span class="tag_box"></span><div class="shop_button"><p class="bottom_p"><a  class='search_btn_cart ' name='Buy' dd_name='加入购物车' href='javascript:AddToShoppingCart(25312917)' ddclick='act=normalResult_addToCart&pos=25312917_5_1_q'><span class='icon'></span>加入购物车</a><a class='search_btn_collect' name='collect' dd_name='加入收藏' id="lcase25312917" href="javascript:void(0);" name="Sc" ddclick='act=normalResult_favor&pos=25312917_5_1_q'>收藏</a></p></div>                </li>
"""

pattern_str = '<a title="(.*)"  ddclick='

names = re.findall(pattern_str, context_str, re.M)

for name in names:
    print(name)

